name: 'Build .NET Core App'

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: '7ab9e4fa-b770-4539-90fc-e422afe20e7d'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'drop'
    path: '$(Build.ArtifactStagingDirectory)'